import { BaseCollector } from '../base/BaseCollector.ts';
import type { CollectorType, IDataCollector, CollectionOptions, CollectionResult, CollectorMetadata } from '../../core/interfaces/IDataCollector.ts';
import type { SearchResult } from '../../lib/types.ts';

// This class encapsulates the actual API interaction logic,
// keeping it separate from the collector's structural code.
class ZhipuSearchAPI {
    public async search(query: string, maxResults: number = 10): Promise<SearchResult[]> {
        try {
            // Mock implementation based on the original zhipu-search.ts
            console.log(`Performing Zhipu AI search for: "${query}"`);
            const results: SearchResult[] = [
                {
                    title: `${query} - Zhipu Search Result`,
                    url: `https://example.com/zhipu/search?q=${encodeURIComponent(query)}`,
                    snippet: `This is a mock search result snippet for the query "${query}" from Zhipu AI.`,
                    content: `This is the detailed mock content for the search result concerning "${query}". It is generated by the ZhipuSearchAPI mock service.`,
                    source: 'Zhipu AI Search',
                    publishDate: new Date().toISOString(),
                    relevanceScore: 0.92
                }
            ];
            return results.slice(0, maxResults);
        } catch (error) {
            console.error('Zhipu AI search failed:', error);
            // In a real scenario, you might want to throw a custom error.
            return [];
        }
    }
}

export class ZhipuSearchCollector extends BaseCollector {
  readonly type: CollectorType = 'API';
  readonly name = 'ZhipuSearch';
  private api = new ZhipuSearchAPI();

  constructor() {
    // Higher priority for a primary search provider
    super(15);
  }

  public async isAvailable(): Promise<boolean> {
    // In a real implementation, this would check for API keys or service status.
    return true;
  }

  public async collect(query: string, options?: CollectionOptions): Promise<CollectionResult> {
    try {
      const maxResults = (options as any)?.maxResults ?? 10;
      const searchResults = await this.api.search(query, maxResults);

      return {
        source: this.name,
        results: searchResults,
      };
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      console.error(`Error collecting data from ${this.name}:`, errorMessage);
      return {
        source: this.name,
        results: [],
        error: errorMessage,
      };
    }
  }

  public async testConnection(): Promise<boolean> {
    try {
      // Perform a lightweight test search to verify connectivity and authentication.
      const results = await this.api.search('connection test', 1);
      // The connection is successful if the call doesn't throw and returns an array.
      return Array.isArray(results);
    } catch (error) {
      console.error(`Connection test for ${this.name} failed:`, error);
      return false;
    }
  }
}